# Generated by Django 2.0 on 2018-05-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bread_type', models.CharField(max_length=32)),
                ('butter', models.BooleanField()),
                ('spread', models.CharField(max_length=32)),
            ],
        ),
    ]
